### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by newtonsheikh** [amd989/Owin.Security.Providers.PingFederate#18]
hi,

how do i implement the same in dotnet core?

thanks

**Comment by emouawad** [comment]
+1

**Comment by amd989** [comment]
For .netcore I would recommend just using the .netcore libraries microsoft provides 
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect/6.0.5

They work same/better than this library. And are updated more regularly. I kinda started this project before any of these libraries were available. Migrating over should not be a big issue.
