### ISSUE TITLE
Where do i Specify the Redirect URL

### ISSUE THREAD

**Issue by deepakAditi** [amd989/Owin.Security.Providers.PingFederate#2]
I went through the sample application,but I couldn't see the Lading Page COnfiguration and Where do I recieve the Claims...

**Comment by amd989** [comment]
Hello,

Can you be more specific on what exactly the Landing Page Configuration is?

Also, regarding where you receive the claims. You would have to extend the Middleware functionality by overriding its default provider.

So you would do something like:

```
        app.UsePingFederateAuthentication(new PingFederateAuthenticationOptions()
        {
            ClientId = "id",
            ClientSecret = "super_secret",
            PingFederateUrl = PingServerUrl,
            SignInAsAuthenticationType = SignInAsAuthenticationType,
            Provider = new PingFederateAuthenticationProvider()
                           {
                               OnAuthenticated = context =>
                                   {
                                       context.Identity.Claims;
                                   } 
                           }
        }
```

in the OnAuthenticated Event you would be able to see your claims.

**Comment by deepakAditi** [comment]
When we use the TargetResource  in .net integration kit,you specify the landing Page(redirect page) ,once after successful login, the ping federate redirects to the Lading Page with Token in the QueryParameter.
.so how to you configure the landing page here....

**Comment by amd989** [comment]
Hello, that what you talk about would be the CallBackPath

```
 app.UsePingFederateAuthentication(new PingFederateAuthenticationOptions()
    {
        ...
        CallbackPath = new PathString("/new/path"),
        ...
    }
```

However, if I understand correctly what you are mentioning, it seems you are/were using SP adapters, this library is not intended to use SP adapters but the OAuth2/OpenIdConnect feature in Ping, which takes advantage of the Authorization Server. (if you are indeed using this feature and just made an analogy with the other method please disregard this comment)

HTH
