### ISSUE TITLE
PingFederate configuration

### ISSUE THREAD

**Issue by mijo89joseph** [amd989/Owin.Security.Providers.PingFederate#6]
Hi, 
I tried configuring Ping Federate to use this sample application. 
My application is always getting redirected to Login page.
var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                return RedirectToAction("Login");
            }
I could find that loginInfo is always returning as null for my application.
Can you please help me in configuring Ping Federate and make the sample application working.

**Comment by amd989** [comment]
Hi, 

The sample application seems not to be working as I expected. I'm going to revise and upload a better version soon.

Regards.

**Comment by amd989** [comment]
I have uploaded a new sample application. I hope that its easier to understand now.
