### ISSUE TITLE
LogInInfo null

### ISSUE THREAD

**Issue by lijo26** [amd989/Owin.Security.Providers.PingFederate#7]
I am new to the OWIN components and I have integrated the provided sample application with Ping Federate with the redirect URL configured in Ping  as http://localhost:57103/signin-pingfederate. My Ping server is running on https://localhost:9031 and sample application in http://localhost:57103

But issue is AuthenticationManager.GetExternalLoginInfoAsync() in ExternalLoginCallback  always returns null.
I verified that the AuthenticationTicket is created at the application side once redirected from Ping. 
If you can provide some possible reasons, It would be really helpful.
Also can you provide purpose and working of "signin-pingfederate" handler ?

My  startup code  is  below
  const string PingServerUrl = "https://localhost:9031";
            app.UsePingFederateAuthentication(new PingFederateAuthenticationOptions()
            {
                ClientId = "demo_ac_client",
                ClientSecret = "secretone",
                PingFederateUrl = PingServerUrl,
                DiscoverMetadata = false, // Set to false to avoid discovering metatada, you need to set the Endpoints manually. (shown below)
                SignInAsAuthenticationType = SignInAsAuthenticationType,
                // if DiscoveryMetadata = false then uncomment this  
                Endpoints = new PingFederateAuthenticationOptions.PingFederateAuthenticationEndpoints()
                                {
                                    AuthorizationEndpoint = PingServerUrl + PingFederateAuthenticationOptions.AuthorizationEndpoint,
                                    TokenEndpoint = PingServerUrl + PingFederateAuthenticationOptions.TokenEndpoint,
                                    UserInfoEndpoint = PingServerUrl + PingFederateAuthenticationOptions.UserInfoEndpoint
                                },

```
        });
```

Thanks

**Comment by amd989** [comment]
Hi,

Let me take a look, i think the problem lies in the AccountController logic. This owin provider was intended to be used with an existing IdP which manages the user information, not with the default ASP.net user management. 

In my rush to create a sample application I left the code there and is conflicting now. I will repair it and upload it soon.

Regards

**Comment by amd989** [comment]
I have uploading a working example. Please let me know if it worked for you.
